<?php
/**
 * @file
 * Creates the WIC publications node type.
 *
 * For a full list of elements and attributes, see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7
 */

/**
 * Implements hook_menu()
 */
function wic_pub_menu() {
  return array(
    'publication-order-form' => array(
      'title' => 'WIC publications order form',
      'description' => 'Order publications from WIC',
      'page callback' => 'wic_pub_order_form',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'file' => 'wic_pub.order_form.inc',
    ),
    'admin/wic-forms/order-form' => array(
      'title' => 'Publication order form',
      'description' => 'Administration settings for the publication order form',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('wic_pub_admin_settings'),
      'access arguments' => array('access administration pages'),
      'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
      'file' => 'wic_pub.admin.inc',
    ),
  );
}

/**
 * Implements hook_theme()
 */
function wic_pub_theme($existing, $type, $theme, $path) {
  return array(
    'wic_pub_order_form_description' => array(
      'variables' => array('description' => NULL, 'in_stock' => NULL, 'quantity_max' => NULL),
      'file' => 'wic_pub.order_form.inc',
    ),
    'wic_pub_order_form_step' => array(
      'render element' => 'form',
      'file' => 'wic_pub.order_form.inc',
    ),
  );
}

/**
 * Implements hook_node_view()
 */
function wic_pub_node_view($node, $view_mode) {
  if ($node->type != 'wic_pub') {
    return;
  }

  switch ($view_mode) {
    case 'full':
      if (node_is_page($node)) {
        $breadcrumb = array();
        $breadcrumb[] = l(t('Home'), NULL);
        $breadcrumb[] = l(t('WIC Publications'), 'wic-publications');
        drupal_set_breadcrumb($breadcrumb);
      }
      break;
  }
  return $node;
}

/**
 * Implements hook_mail()
 */
function wic_pub_mail($key, &$message, $params) {
  switch ($key) {
    // Order confirmation for the user.
    case 'order_confirm':
      $message['subject'] = "WIC publications order confirmation";
      $message['body'][] = "Here are the details of your recent publications order with WIC.";
      break;
    // Order notification for WIC.
    case 'order_notice':
      $message['subject'] = "WIC publications order";
      $message['body'][] = "An order has been placed for publications on the WICWorks website.";
      break;
  }

  $message['body'][] = "Name: $params[name]";
  $message['body'][] = "WIC clinic: $params[clinic_name]";
  $message['body'][] = "Address: $params[address]";
  $message['body'][] = "City, State, Zip: $params[city]";
  $message['body'][] = "Phone: $params[phone]";
  $message['body'][] = "Email: $params[email]";
  $message['body'][] = "Selected publications:";
  foreach ($params['items'] as $nid => $item) {
    $item_text = empty($item['order_number']) ? '' : "$item[order_number]-";
    $item_text .= "$item[description] (Quantity $item[quantity])";
    $message['body'][] = $item_text;
  }
}

/**
 * Implements hook_help()
 */
function wic_pub_help($path, $arg) {
  switch($path) {
    case 'publication-order-form':
      return '<p>' . t("Free Resources for WIC Clinics from the USDA/Food and Nutrition Service") . '</p>
        <p>' . t('Materials can only be shipped to WIC clinics in the United States and their territories. No international orders. Limited quantities available until supply exhausted.  Publications are mailed by the US Postal Service.') . '</p>';
  }
}