<?php
// $Id$

/**
 * @file
 * Creates the WIC publications node type.
 *
 * For a full list of elements and attributes, see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7
 */

/**
 * Implements hook_menu()
 */
function wic_pub_menu() {
	return array(
		'publication-order-form' => array(
			'title' => 'WIC publications order form',
			'description' => 'Order publications from WIC',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('wic_pub_order_form'),
			'access arguments' => array('access content'),
			'file' => 'wic_pub.order_form.inc',
	  ),
		'admin/wic-forms/order-form' => array(
	    'title' => 'Publication order form',
			'description' => 'Update materials listed in the publication order form',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('wic_pub_admin_settings'),
			'access arguments' => array('access administration pages'),
      'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
			'file' => 'wic_pub.admin.inc',
		),
	);
}

/**
 * Implements hook_theme()
 */
function wic_pub_theme($existing, $type, $theme, $path) {
	return array(
		'wic_pub_full_view' => array(
			'variables' => array('node' => NULL),
			'file' => 'wic_pub.theme.inc',
		),
		'wic_pub_teaser_view' => array(
			'variables' => array('node' => NULL),
			'file' => 'wic_pub.theme.inc',
		),
		'wic_pub_order_number' => array(
			'variables' => array('order_number' => NULL),
			'file' => 'wic_pub.theme.inc',
		),
		'wic_pub_description' => array(
			'variables' => array('description' => NULL, 'in_stock' => NULL, 'quantity_max' => NULL),
			'file' => 'wic_pub.theme.inc',
		),
		'wic_pub_order_form_description' => array(
			'variables' => array('description' => NULL, 'in_stock' => NULL, 'quantity_max' => NULL),
			'file' => 'wic_pub.theme.inc',
		),
		'wic_pub_order_form' => array(
      'render element' => 'form',
			'file' => 'wic_pub.theme.inc',
		),
	);
}

/**
 * Implements hook_node_info()
 */
function wic_pub_node_info() {
  return array(
    'wic_pub' => array(
      'name' => t('WIC publication'),
      'base' => 'wic_pub',
      'description' => t('<em>WIC publications</em> are used to generate the publications order form, but currently are not published by default.'),
    ),
  );
}

/**
 * Implements hook_load()
 */
function wic_pub_load($nodes) {
  // Load information from the wic_pub table into the node object.
  $result = db_query('SELECT * FROM {wic_pub} WHERE nid IN (:nids)', array(':nids' => array_keys($nodes)));
  foreach ($result as $record) {
    $nodes[$record->nid]->wic_pub_order_number = $record->order_number;
    $nodes[$record->nid]->wic_pub_description = $record->description;
    $nodes[$record->nid]->wic_pub_in_stock = $record->in_stock;
    $nodes[$record->nid]->wic_pub_quantity_max = $record->quantity_max;
  }
}

/**
 * Implements hook_insert()
 *
 * Insert a new publication into the database.
 */
function wic_pub_insert($node) {
  db_insert('wic_pub')
    ->fields(array(
      'nid' => $node->nid,
      'order_number' => $node->wic_pub_order_number,
      'description' => $node->wic_pub_description,
      'in_stock' => $node->wic_pub_in_stock,
      'quantity_max' => $node->wic_pub_quantity_max,
    ))
    ->execute();
}

/**
 * Implements hook_update()
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function wic_pub_update($node) {
  db_update('wic_pub')
    ->fields(array(
      'order_number' => $node->wic_pub_order_number,
      'description' => $node->wic_pub_description,
      'in_stock' => $node->wic_pub_in_stock,
      'quantity_max' => $node->wic_pub_quantity_max,
    ))
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_delete()
 *
 * When a node is deleted, delete the publication.
 */
function wic_pub_delete($node) {
  db_query("DELETE FROM {wic_pub} WHERE nid = :nid", array(':nid' => $node->nid));
}

/**
 * Implements hook_form()
 */
function wic_pub_form($node, &$form_state) {
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Publication title'),
    '#description' => t('A descriptive name of the publication for identifying it in the content management admin page.  This is not the description on the order form.')
  );
  $form['wic_pub_order_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Order number'),
    '#required' => FALSE,
		'#size' => 10,
    '#maxlength' => 10,
		'#weight' => 0,
    '#default_value' => !empty($node->wic_pub_order_number) ? $node->wic_pub_order_number : '',
  );
  $form['wic_pub_description'] = array(
    '#type' => 'textfield',
		'#title' => t('Description'),
		'#description' => t('The publication description displayed on the order form'),
		'#maxlength' => 60,
		'#required' => TRUE,
		'#weight' => 1,
    '#default_value' => !empty($node->wic_pub_description) ? $node->wic_pub_description : '',
	);
  $form['wic_pub_in_stock'] = array(
    '#type' => 'checkbox',
		'#title' => t('Check if the publication is in stock.'),
		'#required' => FALSE,
		'#weight' => 2,
    '#default_value' => isset($node->wic_pub_in_stock) ? $node->wic_pub_in_stock : 1,
	);
	$form['wic_pub_quantity_max'] = array(
	  '#type' => 'textfield',
		'#title' => 'Maximum order quantity',
		'#required' => FALSE,
		'#size' => 3,
    '#maxlength' => 3,
		'#weight' => 3,
		'#default_value' => !empty($node->wic_pub_quantity_max) ? $node->wic_pub_quantity_max : '',
	);

  return $form;
}

/**
 * Implements hook_validate()
 */
function wic_pub_validate($node, $form, &$form_state) {
	$quantity_max = $form_state['values']['wic_pub_quantity_max'];
	// If the max quantity is empty, set it to NULL to prevent a db error.
	if (empty($quantity_max)) {
		$form_state['values']['wic_pub_quantity_max'] = NULL;
	}
	// If not, make sure it's an integer.
	elseif (!is_numeric($quantity_max) || !is_int((int) $quantity_max)) {
		form_set_error('wic_pub_quantity_max', t('The value entered for "Maxiumum order quantity" must be an integer.'));
	}
}

/**
 * Implements hook_view()
 */
function wic_pub_view($node, $view_mode) {
  // Prepare and sanitize node fields.
  wic_pub_node_sanitize($node);

	switch ($view_mode) {
    case 'full':
			theme('wic_pub_full_view', array('node' => $node));
      break;

    case 'teaser':
			theme('wic_pub_teaser_view', array('node' => $node));
      break;
  }
  return $node;
}

/**
 * Sanitize publication node fields to prevent cross-site scripting.
 */
function wic_pub_node_sanitize(&$node) {
  $node->wic_pub_order_number = filter_xss($node->wic_pub_order_number, array());
  $node->wic_pub_description = filter_xss($node->wic_pub_description, array());
  $node->wic_pub_in_stock = $node->wic_pub_in_stock == FALSE ? FALSE : TRUE;
  $node->wic_pub_quantity_max = filter_xss($node->wic_pub_quantity_max, array());
}

/**
 * Implements hook_mail()
 */
function wic_pub_mail($key, &$message, $params) {
	switch ($key) {
		// Order confirmation for the user.
		case 'order_confirm':
      $message['subject'] = "WIC publications order confirmation";
			$message['body'][] = "Here are the details of your recent publications order with WIC.";
		  break;
		// Order notification for WIC.
		case 'order_notice':
      $message['subject'] = "WIC publications order";
      $message['body'][] = "An order has been placed for publications on the WICWorks website.";
		  break;
	}

	$message['body'][] = "Name: $params[name]";
	$message['body'][] = "WIC clinic: $params[clinic_name]";
	$message['body'][] = "Address: $params[address]";
	$message['body'][] = "City, State, Zip: $params[city]";
	$message['body'][] = "Phone: $params[phone]";
	$message['body'][] = "Email: $params[email]";
	$message['body'][] = "Selected publications:";
	foreach ($params['items'] as $nid => $item) {
		$item_text = empty($item['order_number']) ? '' : "$item[order_number]-";
		$item_text .= "$item[description] (Quantity $item[quantity])";
		$message['body'][] = $item_text;
	}
}

/**
 * Implements hook_help()
 */
function wic_pub_help($path, $arg) {
	switch($path) {
		case 'publication-order-form':
		  return '<p>' . t("Free Resources for WIC Clinics from the USDA/Food and Nutrition Service") . '</p>
			  <p>' . t('Materials can only be shipped to WIC clinics in the United States and their territories. No international orders. Limited quantities available until supply exhausted.  Publications are mailed by the US Postal Service.') . '</p>';
	}
}